# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('category', models.IntegerField(choices=[(1, 'Fundamentals'), (2, 'Language Internals'), (3, 'All things Web'), (4, 'Dealing with Data'), (5, 'Security'), (6, 'Performant Python'), (7, 'Scalable Python'), (8, '/etc')])),
            ],
        ),
    ]
